kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

images:
- name: controller
  newName: example.com/rt-bootstrapper
  newTag: v0.0.1

resources:
- manager.yaml

patches:
- path: manager_patch.yaml
  target:
    kind: Deployment
