kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

images:
- name: controller
  newName: koala7659/rt-bootstrapper
  newTag: test1

resources:
- manager.yaml
- priority_class.yaml

patches:
- path: priority_class_patch.yaml
- path: manager_patch.yaml
  target:
    kind: Deployment
