kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

images:
- name: controller
  newName: example.com/rt-bootstrapper
  newTag: v0.0.1

resources:
- priority_class.yaml
- manager.yaml

patches:
- path: priority_class_patch.yaml
- path: manager_patch.yaml
  target:
    kind: Deployment
