apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rt-bootstrapper
    control-plane: controller-manager
  name: priority-class
value: 2100000
globalDefault: false
description: "Scheduling priority of rt-bootstrapper-manager component. Must not be blocked by unschedulable user workloads."
