apiVersion: cert.gardener.cloud/v1alpha1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: rt-bootstrapper
    app.kubernetes.io/managed-by: kustomize
  name: kyma
  namespace: system
spec:
  selfSigned: {}
