namespace: kyma-system

namePrefix: rt-bootstrapper-

patches:
- path: manager_webhook_patch.yaml
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --webhook-name=rt-bootstrapper-mutating-webhook-configuration
  target:
    kind: Deployment

resources:
- ../rbac
- ../webhook
- metrics_service.yaml
- ../certmanager
- ../manager
- ../config

sortOptions:
  order: fifo
