name: Generate release artifacts

on:
  push:
    tags:
      - '*'  # Trigger on tag pushes

jobs:
  setup:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      # the tag name (or empty string)
      tag: ${{ steps.tag.outputs.tag || '' }}
      # experimental tag derived from tag (or empty string)
      image_registry: europe-docker.pkg.dev/kyma-project/prod/rt-bootstrapper
    steps:
      - name: Checkout push/tag ref
        uses: actions/checkout@v5

      - id: tag
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  generate-release:
    needs: setup
    if: needs.setup.outputs.tag != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases and uploading assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Generate Release module artifacts for tag release
        run: |
          set -e
          make build-installer 
          cp ./dist/install.yaml rt-bootstrapper.yaml
        env:
          IMG: ${{ needs.setup.outputs.image_registry }}:${{ needs.setup.outputs.tag }}

      - name: Create Release and Generate Notes
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./rt-bootstrapper.yaml
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}