name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - .reuse
      - LICENSES/
      - LICENSE
      - .gitignore
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - .reuse
      - LICENSES/
      - LICENSE
      - .gitignore
      - "**.md"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '~1.25.5'

      - name: Running Tests
        run: |
          go mod tidy
          set -o pipefail
          make test | tee test.log

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: rt-bootstrapper-unit-tests
          path: |
            test.log

      - name: Generate unit-test summary
        run: |
          {
            echo "# rt-bootsrapper tests output:"
            printf '\n```\n'
            cat test.log
            printf '\n```\n'
          } >> $GITHUB_STEP_SUMMARY

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.25.5"

      - name: Install the latest version of K3D
        env:
          K3D_VERSION: v5.6.0
        run: |
          mkdir -p $HOME/bin
          curl -Lo $HOME/bin/k3d https://github.com/k3d-io/k3d/releases/download/${{env.K3D_VERSION}}/k3d-linux-amd64
          chmod +x $HOME/bin/k3d
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify K3D installation
        run: k3d version

      - name: Running Test e2e
        run: |
          go mod tidy
          set -o pipefail
          make test-e2e

